// <auto-generated />
using System;
using LocadoraVeiculos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraVeiculos.Infrastructure.Migrations
{
    [DbContext(typeof(LocadoraDbContext))]
    partial class LocadoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDevolucaoEfetiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevistaDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KmFinal")
                        .HasColumnType("int");

                    b.Property<int>("KmInicial")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Alugueis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataDevolucaoEfetiva = new DateTime(2025, 3, 5, 7, 30, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2025, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DataPrevistaDevolucao = new DateTime(2025, 3, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            KmFinal = 18500,
                            KmInicial = 17900,
                            Status = 2,
                            ValorDiaria = 175.00m,
                            ValorTotal = 700.00m,
                            VeiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataInicio = new DateTime(2025, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            DataPrevistaDevolucao = new DateTime(2025, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            KmInicial = 24000,
                            Status = 1,
                            ValorDiaria = 240.00m,
                            ValorTotal = 1200.00m,
                            VeiculoId = 3
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorDiariaBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Carros compactos e econômicos, ideais para o dia a dia na cidade.",
                            Nome = "Econômico",
                            ValorDiariaBase = 110.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Conforto, amplo porta-malas e excelente dirigibilidade para viagens.",
                            Nome = "Sedan Médio",
                            ValorDiariaBase = 175.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Espaço, robustez e versatilidade para toda a família.",
                            Nome = "SUV",
                            ValorDiariaBase = 240.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Alto padrão, acabamento sofisticado e máxima performance.",
                            Nome = "Premium",
                            ValorDiariaBase = 380.00m
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNH")
                        .IsUnique();

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNH = "12345678900",
                            CPF = "123.456.789-01",
                            DataCadastro = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos.silva@email.com",
                            Nome = "Carlos Eduardo Silva",
                            Telefone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = 2,
                            CNH = "98765432100",
                            CPF = "987.654.321-09",
                            DataCadastro = new DateTime(2025, 2, 1, 14, 30, 0, 0, DateTimeKind.Utc),
                            Email = "mariana.santos@email.com",
                            Nome = "Mariana Costa Santos",
                            Telefone = "(21) 99876-5432"
                        },
                        new
                        {
                            Id = 3,
                            CNH = "45678912300",
                            CPF = "456.789.123-45",
                            DataCadastro = new DateTime(2025, 2, 20, 9, 15, 0, 0, DateTimeKind.Utc),
                            Email = "roberto.lima@email.com",
                            Nome = "Roberto Ferreira Lima",
                            Telefone = "(31) 97654-3210"
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Toyota",
                            PaisOrigem = "Japão"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Volkswagen",
                            PaisOrigem = "Alemanha"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Chevrolet",
                            PaisOrigem = "Estados Unidos"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fiat",
                            PaisOrigem = "Itália"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Hyundai",
                            PaisOrigem = "Coreia do Sul"
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AluguelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AluguelId")
                        .IsUnique();

                    b.ToTable("Pagamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AluguelId = 1,
                            DataPagamento = new DateTime(2025, 3, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            MetodoPagamento = 3,
                            Status = 2,
                            ValorPago = 700.00m
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFabricacao = 2023,
                            CategoriaId = 2,
                            Cor = "Prata",
                            FabricanteId = 1,
                            Modelo = "Corolla XEi 2.0",
                            Placa = "BRA2E19",
                            Quilometragem = 18500,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AnoFabricacao = 2024,
                            CategoriaId = 1,
                            Cor = "Branco",
                            FabricanteId = 2,
                            Modelo = "Polo Track 1.0",
                            Placa = "ABC1D23",
                            Quilometragem = 8200,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AnoFabricacao = 2023,
                            CategoriaId = 3,
                            Cor = "Azul Eclipse",
                            FabricanteId = 3,
                            Modelo = "Tracker Premier 1.2 Turbo",
                            Placa = "XYZ9K88",
                            Quilometragem = 24000,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AnoFabricacao = 2022,
                            CategoriaId = 1,
                            Cor = "Vermelho",
                            FabricanteId = 4,
                            Modelo = "Argo Drive 1.0",
                            Placa = "MNO4T56",
                            Quilometragem = 35000,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AnoFabricacao = 2024,
                            CategoriaId = 3,
                            Cor = "Preto Onix",
                            FabricanteId = 5,
                            Modelo = "Creta Ultimate 2.0",
                            Placa = "HYU7B44",
                            Quilometragem = 5100,
                            Status = 1
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Aluguel", b =>
                {
                    b.HasOne("LocadoraVeiculos.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Alugueis")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocadoraVeiculos.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Alugueis")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("LocadoraVeiculos.Domain.Entities.Aluguel", "Aluguel")
                        .WithOne("Pagamento")
                        .HasForeignKey("LocadoraVeiculos.Domain.Entities.Pagamento", "AluguelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluguel");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("LocadoraVeiculos.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Veiculos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocadoraVeiculos.Domain.Entities.Fabricante", "Fabricante")
                        .WithMany("Veiculos")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fabricante");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Aluguel", b =>
                {
                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Alugueis");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Fabricante", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("LocadoraVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Alugueis");
                });
#pragma warning restore 612, 618
        }
    }
}
